### ISSUE TITLE
Interested in "distributed Multi-robot formation control in dynamic environment"?

### ISSUE THREAD

**Issue by kreza231** [star2dust/paper-simulation#10]
Hello, I was wondering if you are interested in reproducing this paper:

Alonso-Mora, J., Montijano, E., Nägeli, T. et al. Distributed multi-robot formation control in dynamic environments. Auton Robot 43, 1079–1100 (2019). https://doi.org/10.1007/s10514-018-9783-9

**Comment by star2dust** [comment]
I think this paper is similar to [Alonso2017Multi](https://github.com/star2dust/paper-simulation/tree/master/Alonso2017Multi). The codes can be reused.
