### ISSUE TITLE
Code running error

### ISSUE THREAD

**Issue by lajiji** [star2dust/paper-simulation#2]
Hi, I ran "alonso-mora2017multi robot" with the following error:
>> main_ robot_ control
Function or variable 'rt2tr' is not defined.
Error pkgMechanics.RigidCuboid/updateVerticesPosition  (line 105)
obj.hTransMat  = rt2tr( obj.rotMat , obj.position (1:3));
Error pkgMechanics.RigidCuboid  (line 62)
obj.updateVerticesPosition ;
Error main_ robot_ control (line 12)
obst(1) =  pkgMechanics.RigidCuboid (1,xo1,[1.5,3.5,1]);

**Comment by star2dust** [comment]
Thanks for your comment.
This simulation requires Robotics Toolbox to work. See https://github.com/star2dust/Robotics-Toolbox.
Clone the Robotics-Toolbox project and you can find rt2tr.m in Robotics-Toolbox\rvctools\release10.3.1\robot.
