### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by Winnie-xwj** [star2dust/paper-simulation#3]
I feel hard to reproduce the simulations of this [paper](https://ieeexplore.ieee.org/document/9226092):On Maintaining Linear Convergence of Distributed Learning and Optimization Under Limited Communication, I want to run this algorithm in the decentralized version mentioned in this paper on MNIST, but I do not know how to build distributed algorithm on MATLAB, I hope to get some insights from you.

**Comment by star2dust** [comment]
> I feel hard to reproduce the simulations of this [paper](https://ieeexplore.ieee.org/document/9226092):On Maintaining Linear Convergence of Distributed Learning and Optimization Under Limited Communication, I want to run this algorithm in the decentralized version mentioned in this paper on MNIST, but I do not know how to build distributed algorithm on MATLAB, I hope to get some insights from you.

Thanks for your comment. As far as I can see, this paper investigates a distributed optimization problem and solve it with learning based algorithms. It sounds like an interesting idea, but learning is not in my research field. I need some time to understand this paper.
